create table if not exists public.processed_webhooks (
  id bigint generated by default as identity primary key,
  trans_ref text not null unique,
  product_type text,
  user_id uuid,
  created_at timestamptz not null default now()
);

create index if not exists processed_webhooks_user_id_idx
  on public.processed_webhooks (user_id);
